from typing import Protocol, Dict, Any, List, Tuple

class IAction(Protocol):
    @property
    def type(self) -> str: ...
    
    @property
    def params(self) -> Dict[str, Any]: ...
    
    # def execute(self, applicable_promos: List, total_input: float) -> Tuple[float, float, float]: ...

    def __str__(self) -> str: ...
